env: "local"
databaseHost: "localhost"
databasePort: 5432
databaseUser: "postgres"
databaseName: "oggetto"
databasePassword: "lolkek123"
databaseSSLMode: "disable"
secretKey: "django-insecure-d=a2pod6zatg32i@lh0gmhcjjo1wr71$&c@6hl-co3%nqpgs$)"
tgMessageURL: "http://localhost:1488/messaging/send_message/"
S3Url: "http://localhost:5252/"